CREATE TABLE "USER" (
	  ID VARCHAR2(100) PRIMARY KEY
	, PW VARCHAR2(100)
	, ADDRESS VARCHAR2(300)
	, EMAIL VARCHAR2(300)
	, BRITH DATE
);

CREATE TABLE "PRODUCT" (
	  PRODUCT_NUM NUMBER PRIMARY KEY
	, PRODUCT_NAME VARCHAR2(100)
	, PRODUCT_PRICE NUMBER
	, PRODUCT_COUNT NUMBER
);

CREATE TABLE "ORDER" (
	  ORDER_NUM NUMBER
	, ORDER_DATE DATE
	, USER_ID VARCHAR2(100)
	, PRODUCT_NUM NUMBER
	, CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
	, CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_NUM) REFERENCES TEST_PRODUCT(PRODUCT_NUM)
);

CREATE TABLE TBL_FLOWER (
	  FLO_NAME VARCHAR2(100) PRIMARY KEY
	, FLO_COLOR VARCHAR2(100)
	, FLO_PRICE NUMBER
);

CREATE TABLE TBL_FLOWERPOT (
	  POT_NO NUMBER PRIMARY KEY
	, POT_COLOR VARCHAR2(100)
	, POT_SHAPE VARCHAR2(100)
	, FLO_NAME VARCHAR2(100)
	, CONSTRAINT POT_FK FOREIGN KEY (FLO_NAME) REFERENCES TBL_FLOWER(FLO_NAME)
);
